### ISSUE TITLE
Formatting problems in dataset

### ISSUE THREAD

**Issue by hoyles** [manuchassot/MorphometricsALB#1]
At the end of the ALB_FORK_LENGTH_ROUND_WEIGHT_DATASET_CWP55.csv dataset some rows seem to have overflowed to the next line. This applies to the FISH_IDENTIFIER labels IOTC_451 to IOTC_499 inclusive. Maybe because the GEOM_WKT is a multipolygon rather than a polygon? Anyway, after the GEOM_WKT variable the rest of the data start again in the first column.

**Comment by manuchassot** [comment]
I do not encounter any issue when reading the data set with fread() from data.table. The multipolygon corresponds to the Chagos area. 

plot(st_geometry(st_as_sf(ALB_FL_RD[FISH_IDENTIFIER == "IOTC_451"], wkt = "GEOM_WKT")))

Which app/tool do you use to visualize the CSV? XLSX?

**Comment by hoyles** [comment]
You're right. I haven't seen fread before and it seems to cope with that format, whereas Excel (which I was using) interprets it as 2 rows. 
I saw some rejected lines in the R output and (wrongly) assumed it was due to that issue.
